all: DataItem.class HashTable.class LexicalAnalyzer.class prj4.class Parser.java Symbol.java Stack.java

DataItem.class: DataItem.java
	javac DataItem.java
HashTable.class: HashTable.java
	javac HashTable.java
LexicalAnalyzer.class: LexicalAnalyzer.java
	javac LexicalAnalyzer.java
Parser.class: Parser.java
	javac Parser.java
Symbol.class: Symbol.java
	javac Symbol.java
Stack.class: Stack.java
	javac Stack.java
prj4.class: prj4.java
	javac prj4.java

