all: DataItem.class HashTable.class LexicalAnalyzer.class prj2.class

DataItem.class: DataItem.java
	javac DataItem.java
HashTable.class: HashTable.java
	javac HashTable.java
LexicalAnalyzer.class: LexicalAnalyzer.java
	javac LexicalAnalyzer.java
prj2.class: prj2.java
	javac prj2.java

