all: DataItem.class HashTable.class LexicalAnalyzer.class prj3.class Parser.java Symbol.java

DataItem.class: DataItem.java
	javac DataItem.java
HashTable.class: HashTable.java
	javac HashTable.java
LexicalAnalyzer.class: LexicalAnalyzer.java
	javac LexicalAnalyzer.java
Parser.class: Parser.java
	javac Parser.java
Symbol.class: Symbol.java
	javac Symbol.java
prj3.class: prj3.java
	javac prj3.java

